import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        {/* Критические стили для предотвращения FOUC: цвета и запасной шрифт */}
        <style>{`:root{--background:#ffffff;--foreground:#171717} @media (prefers-color-scheme:dark){:root{--background:#0a0a0a;--foreground:#ededed}} body{background:var(--background);color:var(--foreground);font-family:Arial,Helvetica,sans-serif;margin:0}`}</style>
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
